### ISSUE TITLE
Getting weight measurement

### ISSUE THREAD

**Issue by longphamkhac** [DavidBoja/SMPL-Anthropometry#15]
Thanks for your outstanding works!!!! Given 3d human mesh, I want to output the body measurement, for instance height and weight. I see that your work can output the height but how about the body's weight?

**Comment by DavidBoja** [comment]
Hi,

the body weight is a bit tricky, but it can be approximated with the volume of the mesh. You can take a look at [this paper](https://www.mdpi.com/1424-8220/22/5/1885) and read the discussion.  

The paper has the appropriate code [here](https://github.com/kristijanbartol/linear-3d-humans/). 
They use the trimesh package to estimate the weight [here](https://github.com/kristijanbartol/linear-3d-humans/blob/main/src/measures.py#L400).

Hope this helps.

**Comment by longphamkhac** [comment]
Thanks for your patient reply!! I will look at the paper that you mentioned. And do you have any suggestions about the image person'pose to get the most resonable body measurement such as height?

**Comment by DavidBoja** [comment]
You mean getting the height of a person from an image?

There are works that estimate measurements from images. You can take a look [here](https://ieeexplore.ieee.org/document/9419003) for an overview of 2D methods or in the paper I already sent you, or search for a newer review paper.

I think that the current state of the art model is [SHAPY](https://ieeexplore.ieee.org/document/9419003) which uses the SMPL body model to get the measurements.

**Comment by longphamkhac** [comment]
Exactly what I mean!!! Thank you so much!!

**Comment by Daniil-Osokin** [comment]
@DavidBoja Thanks for the great repo! Can you please help to understand how the real person height is predicted with the SMPL? I mean networks take the image crop of specific size, e.g. 224x224, so whether person height is, it will take the same size in this crop. Why the predicted height will differ for different persons?

**Comment by DavidBoja** [comment]
Hi @Daniil-Osokin 
i presume that these networks implicitly learn the scale of things, i.e. the measurements / height of a person.

If you had camera that is fixed in space and took an image of a person looking at the camera whose height you knew - then you could map the number of pixels that correspond to the height in the image (you could find the number of pixels from the top of the head to the middle point of the heels for example) to the persons real height. This way you could know how to estimate the height of a person given their image from that specific camera fixed in a single position.

I think the networks do a very similar thing, but since they are much more capable, they can estimate the height of people in different poses. The biggest issue here is that they still expect to get the image from a camera fixed in a single position (the same one they were trained on) even if they take out a crop - because this is the only way to really learn the scale of things.
To try and mitigate this problem, I know some works jitter the camera position so the network becomes more robust to these camera changes and could potentially generalize onto a different camera setup.

In the end, giving the model a different camera setup somewhat works, but it doesn't need to work, if you understand what I'm trying to say.

Hope this helps.

**Comment by Daniil-Osokin** [comment]
Many thanks for the detailed answer! I was confused by the results comparison in the SHAPY paper. They measure error in millimeters (!), even for person height, however have no camera parameters and depth to get the scale:
![shapy_results](https://github.com/DavidBoja/SMPL-Anthropometry/assets/2491976/8806220c-117d-49ab-b9a0-8b295ddfa196)
I get it, it is just some regressed value by the network. Thanks again for the clarifications :+1:

**Comment by longphamkhac** [comment]
Sorry for bothering you again, unfortunately, I cannot use SHAPY due to its license. So do you have any alternative solutions for generating realistic 3d body shape and body measurements? Many thanks!!!!!!

**Comment by rshtern** [comment]
Thank you for this great work.
can you explain how can I use SMPL-Anthropometry to measure a body from an image?
do I need to create a SMPLX model first?
what is the correct flow?
Thanks

**Comment by Daniil-Osokin** [comment]
@longphamkhac Hi! You can use any other method from the [table](https://private-user-images.githubusercontent.com/2491976/300005092-8806220c-117d-49ab-b9a0-8b295ddfa196.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MzAxMzUsIm5iZiI6MTcwNjYyOTgzNSwicGF0aCI6Ii8yNDkxOTc2LzMwMDAwNTA5Mi04ODA2MjIwYy0xMTdkLTQ5YWItYjlhMC04YjI5NWRkZmExOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMTU1MDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTJjN2Q0NDljNWUwNjY2NDQ4MGJjYjI4NTUwNzIyOTE0MDUxM2E5Y2MzZjY0ODA0Nzc2YmI4ODJhMzI3ZGRmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PxierYA-v5cUkMsilSrWl_WzQXZgEXsEmtMT-2N7jBc) above. Or give a try [HMR2.0](https://github.com/russoale/hmr2.0), it has MIT license.

**Comment by Daniil-Osokin** [comment]
@rshtern Hi! Yes, first you need the SMPL/SMPLX model of interesting subject (need to run some human body pose estimation model), then you can use this repo to handy measure model parameters.

**Comment by urebahmed** [comment]
![Capture](https://github.com/DavidBoja/SMPL-Anthropometry/assets/158731510/30940da3-69c6-4c96-9c16-db5fb4833cba)
review this issue ........is there any solution ?

**Comment by DavidBoja** [comment]
Hi @urebahmed 
I am not sure what exactly is the problem here. I don't know what dictionary is changing its size, but are you sure it is a part of this repo code?
