### ISSUE TITLE
How to create 2d image to smpl format?

### ISSUE THREAD

**Issue by RK-GOML** [DavidBoja/SMPL-Anthropometry#17]
If it have a 2D image. I first have to convert to smpl format & then pass that model to SMPL-Anhropometry to get measurements?

**Comment by chaerish** [comment]
Hello. Did you solve this problem by any chance? I changed 2d image to smplx model by smplx method and turned pkl file but encountered an error that it could not be measured due to protocol 5 support.

**Comment by rajshukla1102** [comment]
@RK-GOML hey, you can use ExPose or SHAPY to convert your 2D image into smplx format.

**Comment by DavidBoja** [comment]
I just noticed I haven't replied to this issue - sorry for the delay.

@RK-GOML Yes, you need to have SMPL body parameters or vertices in order to get the measurements. As @rajshukla1102  mentions, you can use ExPose or SHAPY to get the smplx body parameters.

@chaerish I'm not sure what exactly did you do, but you can get the official SMPL and SMPLX body models from [here](https://smpl-x.is.tue.mpg.de/). Then use the body parameters that you obtain using the 2d method with this codebase.
