### ISSUE TITLE
AttributeError: 'Struct' object has no attribute 'hands_componentsl'

### ISSUE THREAD

**Issue by jonathanhidalgo1** [DavidBoja/SMPL-Anthropometry#21]
I'm trying to measure a .obj file and I'm getting this error

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    measurer = MeasureBody("smplx")
  File "/SMPL-Anthropometry/measure.py", line 465, in __new__
    return MeasureSMPLX()
  File "/SMPL-Anthropometry/measure.py", line 400, in __init__
    self.faces = smplx.SMPLX(self.body_model_path, ext="pkl").faces
  File "/usr/local/lib/python3.7/site-packages/smplx/body_models.py", line 966, in __init__
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/smplx/body_models.py", line 580, in __init__
    left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
AttributeError: 'Struct' object has no attribute 'hands_componentsl'

this is my code

from measure import MeasureBody
from measurement_definitions import STANDARD_LABELS
import trimesh
from pprint import pprint

mesh = trimesh.load("body.obj")
vertices = mesh.vertices
print(vertices.shape)
measurer = MeasureBody("smplx")
measurer.from_verts(verts=vertices)

measurer.from_verts(verts=vertices) 

measurement_names = measurer.all_possible_measurements
measurer.measure(measurement_names)
print("Measurements")
pprint(measurer.measurements)

**Comment by DavidBoja** [comment]
Sounds like you are perhaps using the SMPL body model instead of the SMPLX - which model did you download?

Also, just to let you know, if your body.obj is a "random" scan and not an actual SMPL scan (meaning it has the same topology as the SMPL body model with  6890 vertices), you won't be able to measure it. This repository is made to measure either an SMPL or SMPLX model. If you want to measure a "random" scan (meaning a scan of a person with any number of points and not following the SMPL topology), you can firstly fit the SMPL body model with [SMPL-Fitting](https://github.com/DavidBoja/SMPL-Fitting) and then use this repository to measure the fitted SMPL.
