### ISSUE TITLE
Is it possible to change Verts Dimension ? 

### ISSUE THREAD

**Issue by TharHtetAungg** [DavidBoja/SMPL-Anthropometry#4]
I have a question about whether Is it possible to change Verts Dimension? Because for SMPLX the verts dimension is not the same as SMPL verts. So If I want to use SMPLX, Is it possible to change the verts dimension in your source code?

Thanks.

**Comment by DavidBoja** [comment]
Hello, 

currently it is not possible. I plan to add support for the different body models in the near future: SMPLX, SMPLH, STAR.

The `measure.py` script is easy to adapt to a different body model, but each body model should have its own measurement definitions, since I rely on the topology of the body model (currently SMPL) to know exactly where to define the measurements.

I am also planning to add an anthropometry module to the [mmhuman3d](https://github.com/open-mmlab/mmhuman3d) repository (basically integrate this repo into theirs), where all the body models would be supported -- but I'm waiting on the authors to contact me back about the idea -- if you'd like to speed things up, you can maybe add a thumbs up (or comment, or whatever) to let the authors know there is interest in the idea [here](https://github.com/open-mmlab/mmhuman3d/discussions/206). Thanks 😊.

**Comment by TharHtetAungg** [comment]
Thank you for getting back to me. Please give me some advice or tips to modify SMPLX in your source code.

Thanks.

**Comment by DavidBoja** [comment]
You would need to change the following:
1. In `measure.py`:
    a) function `create_model`  to create smplx model
    b) function `get_SMPL_joint_regressor` to get smplx joint regressor
    c) few bits here and there to adapt the code to be able to use SMPLX instead of SMPL
2. In `measurement_definitions.py`
    a) Change `IND2JOINT`, `LANDMARK_INDICES`, `CIRCUMFERENCES` from MeasurementDefinitions class and
         `CIRCUMFERENCE_TO_BODYPARTS` to reflect the SMPLX joints, landmarks,..
3. Create `smplx_body_parts_2_faces.json`, similar to `smpl_body_parts_2_faces.json`, where you label each face from
    the SMPLX model to its body part
5. download the SMPLX model and put it in `data/SMPLX` or wherever you find convenient

**Comment by TharHtetAungg** [comment]
Thanks @DavidBoja
