### ISSUE TITLE
How to load my own .pkl file or .obj file to measure?

### ISSUE THREAD

**Issue by dn0418** [DavidBoja/SMPL-Anthropometry#7]
Hello , Thank you very much for your excellent project.  I have used PIXIE and PYMAF to output 3D model from 2D images. 
So I already have 3D pkl and obj file with SMPL and SMPLX format.
I have tried as you mentioned on closed issues.
but I have an error.
assert verts.shape == torch.Size([6890,3]), "verts need to be of dimension (6890,3)"
AssertionError: verts need to be of dimension (6890,3)

My obj has 20908 * 3 = 62724 vertices.
so How to I fix it? I am looking forward to hearing from you.

**Comment by DavidBoja** [comment]
Hello, 

currently the code only supports using an SMPL body model for measuring - you get an error because the measuring script is assuming you give it the  6890 vertices of the SMPL body model.

I am not sure how did you get 62724 vertices, if you say you have an SMPL or SMPLX body model (which have 6890 and around 10k points respectively).

Maybe check what exactly is being saved (or loaded) after using PIXIE and PYMAF?

**Comment by dn0418** [comment]
Hello, Thank you for your reply.
I have got .obj file after running PIXIE.
I have opened my .obj file using 3D Viewer of Windows 10, here I can see all vertices of obj file in Stats & Shading functionality of this program. Please check this. easy.
so is there a way to measure this obj of PIXIE now?
Thanks

**Comment by DavidBoja** [comment]
I presume you are using `demos/demo_fit_body.py` from PIXIE to get the SMPLx body.  I took a quick glance at the script, and the `opdict` dictionary should have the SMPLx 10k vertices you want -- I am not sure what exactly is saved in the obj file in the end.

Unfortunately, this is still not "good enough" because you need to have SMPL vertices, and not SMPLx vertices, because the measurement script works only with SMPL vertices. I have plans to extend this repo to be able to use SMPLx, STAR and SUPR models in the future. Additionally, I have plans to extend the mmhuman3d to be able to measure parametric models (as noted [here](https://github.com/open-mmlab/mmhuman3d/discussions/206#discussioncomment-6289523)) so keep an eye there as well if you are interested.

If you do not want to wait on me to implement the other body models, there are official converting scripts from SMPLx to SMPL [here](https://github.com/vchoutas/smplx/tree/main/transfer_model), so you can convert to SMPL and then use the measuring script.

**Comment by dn0418** [comment]
Thanks a lot. I will wait your next version.
